### ISSUE TITLE
local server

### ISSUE THREAD

**Issue by LutherDiaz** [yunspace/serverless-golang#12]
What is the recommended way of starting a local web server? Thank you!

**Comment by yunspace** [comment]
@LutherDiaz with Function As A Service the idea is not to start up a webserver, but to write a single function that does just one thing. And serverless framework then aggregates the various functions together to form a holistic service.

You can do unit testing by running `make test`. Then you simply deploy to AWS using `make deploy`. The first 1 million Lambda requests are free, so you can use that as a "web server" for integration testing purposes.
