### ISSUE TITLE
errors deploying with recent changes

### ISSUE THREAD

**Issue by kmarquardsen** [yunspace/serverless-golang#27]
@yunspace 

```
make: dep: Command not found
make: *** [_deps] Error 127
make: *** [deps] Error 2
```

**Comment by yunspace** [comment]
thanks, I thought I pushed a fix in the docker image but obviously not... looking into it...

**Comment by kmarquardsen** [comment]
👍 no worries. I glanced at the changes but it wasn't immediately obvious. Let me know if I'm just missing something

**Comment by yunspace** [comment]
epic fail on my side. I committed https://github.com/yunspace/serverless-golang/commit/fec09f04d2eb54f6ec2839b6f17350617b51e358 but it was building `master` in docker hub and I didn't re-tag `1.21.1` properly.

Please delete the old image `docker rmi yunspace/serverless-golang:1.21.1` and re-try.

**Comment by kmarquardsen** [comment]
thanks! all good now

**Comment by yunspace** [comment]
Awesome, I think I will need to add some testing and CI around this going forward.
