### ISSUE TITLE
Create serverless template

### ISSUE THREAD

**Issue by yunspace** [yunspace/serverless-golang#5]
So that users can just run:

    serverless create --template aws-golang-shim

and 

    serverless create --template aws-golang-net

Rather than copy and paste form this sample project

**Comment by cristim** [comment]
I looked into this and it seems easy to do, we just need to insert the content of this repo (with maybe minor changes) at https://github.com/serverless/serverless/tree/master/lib/plugins/create/templates

**Comment by cristim** [comment]
It turns out the proper place for such community templates is https://github.com/serverless/examples.

We should create a PR there.

**Comment by cristim** [comment]
Working on a PR now to have it mentioned there.

In the meantime I noticed that this already works, and we could document it as installation method in our readme:

> serverless install -u https://github.com/yunspace/serverless-golang -n my-golang-project

**Comment by cristim** [comment]
Documentation changes were implemented in #6

**Comment by yunspace** [comment]
Thanks @cristim! 10 steps ahead as usual! Thanks for #6 which has been merged now.

For the community templates I will raise a PR once I finish refactoring #7

**Comment by cristim** [comment]
The PR was already raised, see https://github.com/serverless/examples/pull/133

**Comment by yunspace** [comment]
Awesome, in that case I will update the serverless examples when my changes are merged

**Comment by yunspace** [comment]
#7 is merged and there are now 2 ways to install serverless-golang for either `net` or `event` approach. See README for more details. Closing this and will follow up with serverless/examples#133 separately.
